// Generated by https://quicktype.io

export interface PokemonPaginatedResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}


// THIS INTERFACE IS CREATED SO I CAN ACCES INDIVIDUALY MY POKEMONS
export interface SimplePokemon {
    id: string;
    name: string;
    picture:  string;
    color?:string;
}
